'use client';
import {useState} from 'react';
import type {ComfyDraft,ComfyStatus} from '@/lib/office/types';
export function comfyDraft(status?:ComfyStatus):ComfyDraft{return {workflow:'',promptNodeId:status?.promptNodeId||'',promptInput:status?.promptInput||'text',outputNodeId:status?.outputNodeId||'',clearWorkflow:false};}
export default function ComfyWorkflowFields({draft,onChange,status,kind}:{draft:ComfyDraft;onChange:(d:ComfyDraft)=>void;status?:ComfyStatus;kind:'image'|'video'}){
 const [error,setError]=useState('');const update=(key:keyof ComfyDraft,value:string|boolean)=>onChange({...draft,[key]:value});
 return <><p>Workflow tersimpan: {status?.workflowConfigured?'Ada · terenkripsi':'Belum ada'}. Model, encoder, VAE, dimensi, durasi, dan seed mengikuti workflow; nama model di kantor adalah label.</p>
 <p>Sumber model: <a href={kind==='image'?'https://huggingface.co/Qwen/Qwen-Image-2.1':'https://huggingface.co/Lightricks/LTX-2.5'} target="_blank" rel="noreferrer">{kind==='image'?'Qwen/Qwen-Image-2.1':'Lightricks/LTX-2.5'}</a>. Pilih file lokal dan loader yang cocok dengan model tersebut.</p>
 <p>Belum punya workflow? <a href={`/comfyui-workflows/${kind==='image'?'qwen-image-2.1':'ltx-2.5'}.canvas.json`} download>Unduh template awal {kind==='image'?'Qwen Image 2.1':'LTX 2.5'}</a>. Buka di ComfyUI, sesuaikan loader dan file model Anda, lalu ekspor format API. Template resmi memakai model standar; varian GGUF/uncensored memerlukan penyesuaian sesuai sumber model.</p>
 <label>Unggah workflow API JSON<input data-testid={`${kind}-comfy-file`} type="file" accept=".json,application/json" onChange={async e=>{setError('');const f=e.target.files?.[0];if(!f)return;if(f.size>60000){setError('File maksimal 60 KB.');return;}try{onChange({...draft,workflow:await f.text(),clearWorkflow:false});}catch{setError('File tidak dapat dibaca.');}e.target.value='';}}/></label>
 <label>Atau tempel workflow API<textarea data-testid={`${kind}-comfy-workflow`} rows={8} maxLength={60000} value={draft.workflow||''} placeholder="Kosongkan untuk mempertahankan workflow tersimpan" style={{width:'100%',maxWidth:'100%',boxSizing:'border-box'}} onChange={e=>onChange({...draft,workflow:e.target.value,clearWorkflow:false})}/><small>Format API berisi node dengan class_type dan inputs. Format canvas berisi nodes/links harus diekspor ulang dari ComfyUI.</small></label>
 <label>ID node prompt<input data-testid={`${kind}-comfy-prompt-node`} value={draft.promptNodeId} maxLength={100} onChange={e=>update('promptNodeId',e.target.value)} placeholder="Contoh: 6 atau 459:452"/></label>
 <label>Nama input prompt<input data-testid={`${kind}-comfy-prompt-input`} value={draft.promptInput} maxLength={80} onChange={e=>update('promptInput',e.target.value)}/><small>Biasanya text pada CLIPTextEncode; prompt pada TextEncodeQwenImage21. Hanya input ini diganti dengan brief kantor.</small></label>
 <label>ID node penyimpan hasil<input data-testid={`${kind}-comfy-output-node`} value={draft.outputNodeId} maxLength={100} onChange={e=>update('outputNodeId',e.target.value)} placeholder="Node SaveImage / SaveVideo"/><small>{kind==='image'?'Simpan sebagai PNG/JPEG/WebP.':'Simpan sebagai MP4 (SaveVideo atau VHS Video Combine).'} Pilih node output, bukan preview sementara.</small></label>
 <label className="backend-checkbox"><input type="checkbox" checked={Boolean(draft.clearWorkflow)} onChange={e=>onChange({...draft,workflow:e.target.checked?'':draft.workflow,clearWorkflow:e.target.checked})}/>Hapus workflow tersimpan</label>{error&&<p role="alert" className="backend-error">{error}</p>}</>;
}
