'use client';
import {useState} from 'react';
import type {ComfyDraft,ComfyStatus,ComfyModelSource} from '@/lib/office/types';
export function comfyDraft(status?:ComfyStatus):ComfyDraft{return {source:status?.source||'custom',workflow:'',promptNodeId:status?.promptNodeId||'',promptInput:status?.promptInput||'text',outputNodeId:status?.outputNodeId||'',clearWorkflow:false};}
export default function ComfyWorkflowFields({draft,onChange,status,kind,onSourceChange}:{onSourceChange:(source:ComfyModelSource)=>void;draft:ComfyDraft;onChange:(d:ComfyDraft)=>void;status?:ComfyStatus;kind:'image'|'video'}){
 const [error,setError]=useState('');const unsloth=draft.source==='unsloth';const wanGGUF=kind==='video'&&draft.source==='wan-gguf';const wanVideo=kind==='video'&&(unsloth||wanGGUF);const title=kind==='image'?'Qwen Image 2.1':'Wan 2.2 TI2V 5B';const template=kind==='image'?'qwen-image-2.1':wanVideo?'wan-2.2-ti2v-5b':'ltx-2.5';const update=(key:keyof ComfyDraft,value:string|boolean)=>onChange({...draft,[key]:value});
 return <><label>Sumber model lokal<select data-testid={`${kind}-comfy-source`} value={draft.source||'custom'} onChange={e=>onSourceChange(e.target.value as ComfyModelSource)}><option value="custom">Model sendiri / template resmi</option><option value="unsloth">Unsloth · {kind==='image'?'Qwen-Image-2.1-GGUF':'Wan2.2-TI2V-5B-FP8'}</option>{kind==='video'&&<option value="wan-gguf">Lokal · Wan2.2-TI2V-5B-GGUF</option>}</select></label>
 {unsloth&&<p>Bobot Unsloth dijalankan oleh ComfyUI lokal. Gunakan file dan loader yang cocok, lalu ekspor workflow API; memilih preset tidak mengunduh atau memuat model. Pergantian sumber memerlukan workflow baru.</p>}
 {wanGGUF&&<p>Wan2.2-TI2V-5B-GGUF dijalankan secara lokal melalui ComfyUI. Pasang <a href="https://github.com/city96/ComfyUI-GGUF" target="_blank" rel="noreferrer">ComfyUI-GGUF</a> yang kompatibel, ganti UNETLoader dengan UnetLoaderGGUF, lalu pilih file .gguf Anda beserta text encoder UMT5 dan VAE Wan 2.2 yang cocok. Template awal memakai FP16; pilihan ini tidak mengunduh atau memuat bobot.</p>}
 <p>Workflow tersimpan: {status?.workflowConfigured?'Ada · terenkripsi':'Belum ada'}. Model, encoder, VAE, dimensi, durasi, dan seed mengikuti workflow; nama model di kantor adalah label.</p>
 <p>Sumber model: <a href={wanGGUF?'https://huggingface.co/Wan-AI/Wan2.2-TI2V-5B':unsloth?(kind==='image'?'https://huggingface.co/unsloth/Qwen-Image-2.1-GGUF':'https://huggingface.co/unsloth/Wan2.2-TI2V-5B-FP8'):(kind==='image'?'https://huggingface.co/Qwen/Qwen-Image-2.1':'https://huggingface.co/Lightricks/LTX-2.5')} target="_blank" rel="noreferrer">{wanGGUF?'Wan-AI/Wan2.2-TI2V-5B (model dasar)':unsloth?`Unsloth · ${title}`:kind==='image'?'Qwen/Qwen-Image-2.1':'Lightricks/LTX-2.5'}</a>. Pilih file lokal dan loader yang cocok dengan model tersebut.</p>
 <p>Belum punya workflow? <a href={`/comfyui-workflows/${template}.canvas.json`} download>Unduh template awal {kind==='image'?'Qwen Image 2.1':wanVideo?'Wan 2.2 TI2V 5B':'LTX 2.5'}</a>. Buka di ComfyUI, sesuaikan loader dan file model Anda, lalu ekspor format API. Template resmi memakai model standar; varian GGUF/uncensored memerlukan penyesuaian sesuai sumber model.</p>
 {wanVideo&&<p>Template Wan mendukung teks dan gambar. Untuk brief teks, lepaskan input start_image beserta node LoadImage sebelum ekspor. Untuk image-to-video, siapkan gambar awal dalam workflow ComfyUI. Prompt positif: node 6 / text; simpan MP4: node 58.</p>}
 <label>Unggah workflow API JSON<input data-testid={`${kind}-comfy-file`} type="file" accept=".json,application/json" onChange={async e=>{setError('');const f=e.target.files?.[0];if(!f)return;if(f.size>60000){setError('File maksimal 60 KB.');return;}try{onChange({...draft,workflow:await f.text(),clearWorkflow:false});}catch{setError('File tidak dapat dibaca.');}e.target.value='';}}/></label>
 <label>Atau tempel workflow API<textarea data-testid={`${kind}-comfy-workflow`} rows={8} maxLength={60000} value={draft.workflow||''} placeholder="Kosongkan untuk mempertahankan workflow tersimpan" style={{width:'100%',maxWidth:'100%',boxSizing:'border-box'}} onChange={e=>onChange({...draft,workflow:e.target.value,clearWorkflow:false})}/><small>Format API berisi node dengan class_type dan inputs. Format canvas berisi nodes/links harus diekspor ulang dari ComfyUI.</small></label>
 <label>ID node prompt<input data-testid={`${kind}-comfy-prompt-node`} value={draft.promptNodeId} maxLength={100} onChange={e=>update('promptNodeId',e.target.value)} placeholder="Contoh: 6 atau 459:452"/></label>
 <label>Nama input prompt<input data-testid={`${kind}-comfy-prompt-input`} value={draft.promptInput} maxLength={80} onChange={e=>update('promptInput',e.target.value)}/><small>Biasanya text pada CLIPTextEncode; prompt pada TextEncodeQwenImage21. Hanya input ini diganti dengan brief kantor.</small></label>
 <label>ID node penyimpan hasil<input data-testid={`${kind}-comfy-output-node`} value={draft.outputNodeId} maxLength={100} onChange={e=>update('outputNodeId',e.target.value)} placeholder="Node SaveImage / SaveVideo"/><small>{kind==='image'?'Simpan sebagai PNG/JPEG/WebP.':'Simpan sebagai MP4 (SaveVideo atau VHS Video Combine).'} Pilih node output, bukan preview sementara.</small></label>
 <label className="backend-checkbox"><input type="checkbox" checked={Boolean(draft.clearWorkflow)} onChange={e=>onChange({...draft,workflow:e.target.checked?'':draft.workflow,clearWorkflow:e.target.checked})}/>Hapus workflow tersimpan</label>{error&&<p role="alert" className="backend-error">{error}</p>}</>;
}
