'use client';
import {useState,type FormEvent} from 'react';
import {Check,ImagePlus,Save,ShieldCheck,Sparkles} from 'lucide-react';
import ComfyWorkflowFields,{comfyDraft} from './ComfyWorkflowFields';
import {normalizeComfyBaseUrl,normalizeImageBaseUrl} from '@/lib/office/endpoints';
import type {ImageAspectRatio,ImageProviderId,OfficeAction,OfficeConfig} from '@/lib/office/types';
const LABELS:Record<ImageProviderId,string>={openai:'GPT Image · OpenAI',imagen:'Imagen · Google AI Studio',huggingface:'FLUX.1 · Hugging Face',qwen:'Qwen Image GGUF · Server lokal',comfyui:'ComfyUI · Qwen GGUF / Unsloth'};
const MODELS:Record<ImageProviderId,string[]>={openai:['gpt-image-1','gpt-image-1-mini','gpt-image-1.5'],imagen:['imagen-3.0-generate-002','imagen-4.0-generate-001'],huggingface:['black-forest-labs/FLUX.1-schnell','black-forest-labs/FLUX.1-dev'],qwen:['Qwen-Image-2.1-Uncensored-GGUF'],comfyui:['Qwen-Image-2.1-Uncensored-GGUF','Qwen/Qwen-Image-2.1','unsloth/Qwen-Image-2.1-GGUF']};
export default function ImageSettings({config,busy,action}:{config:OfficeConfig;busy:boolean;action:(a:OfficeAction)=>Promise<void>}){
 const initial=config.imageProviders.find(p=>p.provider===config.imageProvider)!;
 const [provider,setProvider]=useState<ImageProviderId>(config.imageProvider);const [model,setModel]=useState(initial.model);const [ratio,setRatio]=useState<ImageAspectRatio>(initial.aspectRatio);
 const [baseUrl,setBaseUrl]=useState(initial.baseUrl||'http://127.0.0.1:1234/v1');
 const [comfy,setComfy]=useState(()=>comfyDraft(initial.comfy));
 const [apiKey,setApiKey]=useState('');const [clearKey,setClearKey]=useState(false);const [testing,setTesting]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const status=config.imageProviders.find(p=>p.provider===provider)!;
 function changeProvider(next:ImageProviderId){const saved=config.imageProviders.find(p=>p.provider===next)!;setProvider(next);setModel(saved.model);setRatio(saved.aspectRatio);setBaseUrl(saved.baseUrl||(next==='comfyui'?'http://127.0.0.1:8188':'http://127.0.0.1:1234/v1'));setComfy(comfyDraft(saved.comfy));setApiKey('');setClearKey(false);setError('');setMessage('');}
 async function save(e:FormEvent){e.preventDefault();setError('');setMessage('');try{await action({type:'saveImageProvider',settings:{provider,model,aspectRatio:ratio,...(provider==='comfyui'?{comfy}:{}),...(['qwen','comfyui'].includes(provider)?{baseUrl}:{}),...(apiKey?{apiKey}:{}),clearKey}});if(['qwen','comfyui'].includes(provider))setBaseUrl(provider==='comfyui'?normalizeComfyBaseUrl(baseUrl):normalizeImageBaseUrl(baseUrl));setComfy(d=>({...d,workflow:'',clearWorkflow:false}));setClearKey(false);setMessage('Model gambar tersimpan dan dipakai untuk visual berikutnya.');}catch(err){setError(err instanceof Error?err.message:'Konfigurasi belum tersimpan.');}finally{setApiKey('');}}
 async function test(){setTesting(true);setError('');setMessage('');try{const response=await fetch('/api/office/images/test',{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Uji gambar gagal.');setMessage(`Gambar uji berhasil dibuat oleh ${result.model} (${result.width} × ${result.height}).`);}catch(err){setError(err instanceof Error?err.message:'Koneksi gambar gagal.');}finally{setTesting(false);}}
 return <div className="backend-grid"><form className="backend-card" data-testid="image-settings" onSubmit={save}>
 <div className="backend-card-title"><span className="backend-icon"><ImagePlus size={21}/></span><div><h3>Model pembuat gambar</h3><p>Tim Graphic Design · Luna & Pixel</p></div><span className={`backend-status ${status.configured?'connected':''}`}>{status.configured?(['qwen','comfyui'].includes(provider)?'Dikonfigurasi':'Dikonfigurasi'):provider==='comfyui'&&!status.comfy?.workflowConfigured?'Workflow diperlukan':'Kunci diperlukan'}</span></div>
 <label>Provider gambar<select data-testid="image-provider" value={provider} onChange={e=>changeProvider(e.target.value as ImageProviderId)}>{Object.entries(LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 {['qwen','comfyui'].includes(provider)&&<label>Endpoint server gambar<input data-testid="image-url" type="url" required value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder={provider==='comfyui'?'http://127.0.0.1:8188':'http://127.0.0.1:1234/v1'}/><small>{provider==='comfyui'?'Endpoint ComfyUI native, misalnya http://127.0.0.1:8188. Gunakan workflow API untuk memuat GGUF.':'API kompatibel /v1/images/generations, seperti sd-server. GGUF harus dimuat pada server beserta text encoder dan VAE yang cocok. Ollama untuk teks tidak menyediakan API ini.'}</small></label>}
 <label>Model{provider==='huggingface'?<select data-testid="image-model" value={model} onChange={e=>setModel(e.target.value)}>{MODELS.huggingface.map(id=><option key={id}>{id}</option>)}</select>:<><input data-testid="image-model" list="image-model-presets" required maxLength={160} value={model} onChange={e=>setModel(e.target.value)}/><datalist id="image-model-presets">{MODELS[provider].map(id=><option value={id} key={id}/>)}</datalist></>}<small>{provider==='comfyui'?'Label model; file yang dimuat ditentukan oleh loader pada workflow.':provider==='qwen'?'Nama/alias model pada server. Preset ini tidak mengunduh atau memuat GGUF; pastikan runtime mendukung varian model Anda.':provider==='imagen'?'Preset Imagen 3 memakai imagen-3.0-generate-002. Gunakan model Imagen yang tersedia pada akun Google AI Studio Anda; Imagen 4 tersedia sebagai pilihan.':provider==='huggingface'?'schnell untuk generasi cepat; dev membutuhkan akses/lisensi model yang sesuai. SDK memilih Inference Provider yang tersedia.':'Gunakan ID model GPT Image yang tersedia pada akun OpenAI Anda.'}</small></label>
 {provider==='comfyui'&&<ComfyWorkflowFields draft={comfy} onChange={setComfy} status={status.comfy} kind="image" onSourceChange={source=>{setComfy({...comfy,source,workflow:'',clearWorkflow:true});setModel(source==='unsloth'?'unsloth/Qwen-Image-2.1-GGUF':MODELS.comfyui[0]);setMessage('Sumber berubah. Tambahkan workflow API yang sesuai sebelum menyimpan.');}}/>}
 <label>Rasio hasil<select data-testid="image-ratio" value={ratio} onChange={e=>setRatio(e.target.value as ImageAspectRatio)}><option value="1:1">1:1 · Persegi</option><option value="4:5">4:5 · Feed Instagram</option><option value="9:16">9:16 · Story / cover video</option><option value="16:9">16:9 · Landscape</option></select><small>Hasil disimpan sebagai PNG; crop disesuaikan ke rasio yang dipilih.</small></label>
 <label>{['qwen','comfyui'].includes(provider)?'API key server gambar (opsional untuk lokal)':provider==='huggingface'?'Token Hugging Face baru':provider==='imagen'?'API key Google AI Studio baru':'API key OpenAI gambar baru'}<input data-testid="image-key" type="password" autoComplete="new-password" spellCheck={false} maxLength={4096} value={apiKey} placeholder="Kosongkan untuk mempertahankan kunci tersimpan" onChange={e=>{setApiKey(e.target.value);if(e.target.value)setClearKey(false);}}/><small>{['qwen','comfyui'].includes(provider)?'Server loopback dapat dipakai tanpa kunci. HTTPS nonlokal membutuhkan kunci khusus. Kunci provider cloud lain tidak diteruskan.':provider==='huggingface'?'Token diawali hf_ dengan izin Inference Providers. Pastikan akses model dan kredit tersedia.':provider==='imagen'?'Gunakan API key dari project Google AI Studio / Gemini API dengan akses Imagen dan billing yang sesuai. Kunci gambar disimpan terpisah dari kunci Gemini untuk teks.':'Tanpa kunci gambar khusus, OpenAI dapat memakai kunci Graphic Design atau backend utama OpenAI.'}</small></label>
 <label className="backend-checkbox"><input data-testid="image-clear" type="checkbox" checked={clearKey} onChange={e=>{setClearKey(e.target.checked);if(e.target.checked)setApiKey('');}}/>Hapus kunci provider ini dan nonaktifkan fallback kunci</label>
 <div className="backend-key-state"><ShieldCheck size={14}/>{status.keySource==='stored'?'Kunci terenkripsi tersimpan':status.keySource==='environment'?'Kunci dari environment':status.keySource==='shared'?'Memakai kunci OpenAI yang sudah dikonfigurasi':['qwen','comfyui'].includes(provider)&&status.local?'Server lokal · tanpa API key':'Belum ada kunci untuk provider ini'}</div>
 {error&&<p className="backend-error" role="alert">{error}</p>}{message&&<p className="backend-success" role="status"><Check size={15}/>{message}</p>}
 <div className="backend-actions"><button data-testid="image-test" type="button" className="button secondary" onClick={()=>void test()} disabled={busy||testing||!config.imageConfigured}>{testing?'Membuat gambar…':<><Sparkles size={15}/>Uji gambar tersimpan</>}</button><button data-testid="image-save" type="submit" className="button primary" disabled={busy||testing}><Save size={15}/>Simpan model gambar</button></div>
 </form><aside className="backend-help"><section className="backend-card"><h3>Satu pilihan aktif untuk visual.</h3><p>Model aktif: {LABELS[config.imageProvider]} · {config.imageModel}.</p><p>Simpan provider yang dipilih untuk mengubah model gambar aktif. Kunci provider lain tetap tersimpan, dan tidak dipakai sebagai pengganti jika provider aktif gagal.</p><p>Qwen lokal menunggu hingga 10 menit saat generasi. Status endpoint disetel belum memastikan server berjalan atau model sudah dimuat.</p><p>Uji gambar memakai konfigurasi tersimpan, membuat satu gambar kecil konsep, dan dapat memakai kuota berbayar. Gambar uji tidak ditambahkan ke kampanye.</p></section><section className="backend-card"><h3>Brief menjadi konsep visual.</h3><p>Buka hasil kerja desain lalu pilih Buat visual. Prompt memakai brief dan arahan desain. Gambar serta hasil turunannya selalu memerlukan review Marketing Manager.</p><p>Rasio cover TikTok menghasilkan gambar statis, bukan video. Provider teks dan token Publisher tetap terpisah.</p></section></aside></div>;
}
