'use client';

import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,BarChart3,Bell,Check,ChevronDown,ChevronRight,Command,FileText,Flower2,Focus,Hash,Layers3,LayoutDashboard,LoaderCircle,Maximize2,Menu,MessageCircle,Plus,Radio,RotateCcw,Search,Send,Settings2,ShieldCheck,Sparkles,Users,Workflow,X} from 'lucide-react';
import type {Agent,Brief,DivisionId,OfficeAction,OfficeResponse,OfficeState} from '@/lib/office/types';
import {AGENTS,CHANNELS,DIVISIONS,divisionById} from '@/lib/office/catalog';
import WorkPanels from './WorkPanels';
const OfficeScene=dynamic(()=>import('./OfficeScene'),{ssr:false,loading:()=> <div className="scene-loading"><LoaderCircle className="spin" size={24}/><span>Menyiapkan ruang kerja…</span></div>});
type View='office'|'workflow'|'deliverables'|'analytics'|'team'|'settings';
const NAV=[{id:'office',label:'Kantor virtual',icon:LayoutDashboard},{id:'workflow',label:'Alur kerja',icon:Workflow},{id:'deliverables',label:'Hasil pekerjaan',icon:FileText},{id:'analytics',label:'Analitik',icon:BarChart3},{id:'team',label:'Tim & agen',icon:Users},{id:'settings',label:'Pengaturan',icon:Settings2}] as const;

export function Avatar({agent,size=36}:{agent:Agent;size?:number}){return <span aria-hidden="true" className="avatar" style={{width:size,height:size,backgroundColor:divisionById(agent.division).tint,backgroundPosition:`${(agent.avatarIndex%3)*50}% ${Math.floor(agent.avatarIndex/3)*50}%`}}/>;}
function shortTime(value:string){return new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit'}).format(new Date(value));}

export default function OfficeApp(){
 const [data,setData]=useState<OfficeResponse|null>(null);
 const [view,setView]=useState<View>('office');
 const [campaignId,setCampaignId]=useState('');
 const [selectedDivision,setSelectedDivision]=useState<DivisionId|'all'>('all');
 const [channel,setChannel]=useState<DivisionId|'general'>('general');
 const [selectedAgent,setSelectedAgent]=useState<string|null>(null);
 const [createOpen,setCreateOpen]=useState(false);
 const [busy,setBusy]=useState(false);
 const [toast,setToast]=useState<{text:string;error:boolean}|null>(null);
 const [locked,setLocked]=useState(false);
 const [loadError,setLoadError]=useState('');
 const [mode,setMode]=useState<'demo'|'live'>('demo');
 const [resetKey,setResetKey]=useState(0);
 const [expanded,setExpanded]=useState(false);
 const [navOpen,setNavOpen]=useState(false);
 const [search,setSearch]=useState('');
 const [notifications,setNotifications]=useState(false);
 const firstLoad=useRef(true);
 const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const notify=useCallback((text:string,error=false)=>{setToast({text,error});if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(null),6500);},[]);
 const refresh=useCallback(async()=>{
  const response=await fetch('/api/office',{cache:'no-store'});
  if(response.status===401){setLocked(true);return;}
  const result=await response.json();
  if(!response.ok)throw new Error(result.error||'Kantor belum dapat dimuat.');
  setData(current=>current&&current.state.revision>=result.state.revision&&JSON.stringify(current.config)===JSON.stringify(result.config)?current:result);setLocked(false);setLoadError('');
  setCampaignId(current=>current||result.state.campaigns[0]?.id||'');
  if(firstLoad.current){setMode(result.config.aiConfigured?'live':'demo');firstLoad.current=false;}
 },[]);
 useEffect(()=>{const load=()=>void refresh().catch(error=>setLoadError(error.message));load();const timer=setInterval(load,3000);return()=>{clearInterval(timer);if(toastTimer.current)clearTimeout(toastTimer.current);};},[refresh]);
 const action=useCallback(async(payload:OfficeAction)=>{
  setBusy(true);
  try{
   const response=await fetch('/api/office/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
   const result=await response.json();
   if(!response.ok){if(response.status===401)setLocked(true);throw new Error(result.error||'Perintah belum berhasil.');}
   setData(result);
   if(payload.type==='createCampaign') {setCampaignId(result.state.campaigns.find((c:{name:string})=>c.name===payload.brief.name)?.id??'');notify('Brief diterima. Delapan agen siap mengerjakan campaign Anda.');}
   else if(payload.type==='runCampaign')notify('Laporan tim siap. Tinjau hasil pekerjaan untuk memberikan persetujuan.');
   else if(payload.type==='approveArtifact')notify('Hasil pekerjaan disetujui.');
   else if(payload.type==='requestRevision')notify('Arahan revisi dikirim ke agen.');
   else if(payload.type==='schedule')notify('Jadwal tersimpan. Paket siap diekspor untuk dipublikasikan.');
  }catch(error){const text=error instanceof Error?error.message:'Terjadi kesalahan.';notify(text,true);void refresh().catch(()=>{});throw error;}finally{setBusy(false);}
 },[notify,refresh]);
 const safeAction=(payload:OfficeAction)=>void action(payload).catch(()=>{});
 const changeView=(next:View)=>{setView(next);setNavOpen(false);setExpanded(false);};
 if(locked)return <AccessGate onUnlock={refresh}/>;
 if(!data)return <main className="loading-page"><div className="brand-mark"><Flower2 size={30}/></div><h1>Kadaka</h1><p>{loadError||'Membuka kantor marketing Anda…'}</p>{loadError?<button className="button primary" onClick={()=>void refresh().catch(error=>setLoadError(error.message))}>Coba lagi</button>:<LoaderCircle className="spin"/>}</main>;
 const {state,config}=data;

 const campaign=state.campaigns.find(c=>c.id===campaignId);
 const tasks=state.tasks.filter(t=>t.campaignId===campaignId);
 const activeAgent=state.agents.find(a=>a.id===selectedAgent);
 const reviewCount=state.artifacts.filter(a=>a.campaignId===campaignId&&a.status==='review').length;
 const runningCount=state.agents.filter(a=>a.status==='working').length;
 const approvedCount=tasks.filter(t=>t.status==='approved').length;
 const progress=tasks.length?Math.round(approvedCount/tasks.length*100):0;
 const searchResults=search.trim()?state.agents.filter(a=>`${a.name} ${a.role}`.toLowerCase().includes(search.toLowerCase())):[];
 return <div className="app-shell">
  {navOpen&&<button className="sidebar-scrim" aria-label="Tutup navigasi" onClick={()=>setNavOpen(false)}/>}
  <aside className={`sidebar ${navOpen?'is-open':''}`}>
   <Link className="brand" href="/" aria-label="Kadaka beranda"><span className="brand-mark"><Flower2 size={24} strokeWidth={1.6}/></span><span>kadaka<span className="brand-dot">.</span></span></Link>
   <div className="workspace-switch"><span className="workspace-symbol"><Layers3 size={18}/></span><div><strong>Marketing Office</strong><span>Human-led. AI-powered.</span></div><ChevronDown size={15}/></div>
   <span className="nav-heading">WORKSPACE</span>
   <nav aria-label="Navigasi utama">{NAV.map(({id,label,icon:Icon})=><button key={id} data-testid={`tab-${id}`} className={`nav-item ${view===id?'active':''}`} onClick={()=>changeView(id)}><Icon size={18} strokeWidth={1.7}/><span>{label}</span>{id==='deliverables'&&reviewCount>0?<span className="nav-count">{reviewCount}</span>:id==='office'?<span className="tiny-live-dot"/>:null}</button>)}</nav>
   <div className="sidebar-divisions"><span className="nav-heading">DIVISI KANTOR <span>4</span></span>{DIVISIONS.filter(d=>d.id!=='manager').map(d=><button className="division-nav" key={d.id} onClick={()=>{setSelectedDivision(d.id);setChannel(d.id);changeView('office');}}><i style={{background:d.color}}/><span>{d.name}</span><span className="division-count">02</span></button>)}</div>
   <div className="sidebar-bottom"><div className="manager-note"><div className="note-top"><ShieldCheck size={20}/><span>Anda yang memimpin.</span></div><p>Agen mengerjakan. Anda mengarahkan dan menyetujui.</p><button onClick={()=>setCreateOpen(true)}>Mulai dengan sebuah brief <ArrowUpRight size={14}/></button></div><button className="profile" onClick={()=>setSelectedAgent('manager')}><Avatar agent={AGENTS[0]} size={36}/><span><strong>Marketing Manager</strong><small>Anda · Human</small></span><Settings2 size={17}/></button></div>
  </aside>
  <div className="main-shell">
   <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Buka navigasi" onClick={()=>setNavOpen(true)}><Menu size={19}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{NAV.find(n=>n.id===view)?.label}</strong></div><div className="topbar-actions"><div className="search-wrap"><Search size={16}/><input aria-label="Cari agen" placeholder="Cari di kantor…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd><Command size={10}/> K</kbd>{search&&<div className="search-results">{searchResults.length?searchResults.map(a=><button key={a.id} onClick={()=>{setSelectedAgent(a.id);setSearch('');}}><Avatar agent={a} size={28}/><span>{a.name}<small>{a.role}</small></span></button>):<p>Tidak ada agen yang cocok.</p>}</div>}</div><span className="topbar-divider"/><div className="notification-wrap"><button className="icon-button notification-button" aria-label="Laporan terbaru" onClick={()=>setNotifications(!notifications)}><Bell size={19}/>{reviewCount>0&&<i/>}</button>{notifications&&<div className="notification-popover"><strong>Laporan untuk Anda</strong><p>{reviewCount?`${reviewCount} hasil pekerjaan menunggu review.`:'Belum ada laporan yang menunggu review.'}</p><button onClick={()=>{changeView('deliverables');setNotifications(false);}}>Lihat hasil pekerjaan <ArrowRight size={14}/></button></div>}</div><Avatar agent={AGENTS[0]} size={32}/></div></header>
   <main className="main-content">
    {view==='office'&&<section className="page-heading"><div><div className="eyebrow"><span className="tiny-live-dot"/> YOUR IDEAS. YOUR TEAM. YOUR OFFICE.</div><h1>{view==='office'?'Ide besar, tim yang siap.':view==='workflow'?'Dari brief menjadi karya.':view==='deliverables'?'Karya tim, keputusan Anda.':view==='analytics'?'Data menjadi arah.':view==='team'?'Kenali tim kreatif Anda.':'Ruang untuk bekerja lebih baik.'}</h1><p>{view==='office'?'Satu kantor. Empat divisi. Semua bergerak bersama Anda.':view==='workflow'?'Pantau setiap langkah dan arahkan pekerjaan lintas divisi.':view==='deliverables'?'Tinjau, beri arahan, dan setujui hasil sebelum dipublikasikan.':view==='analytics'?'Lihat performa campaign dari data yang Anda masukkan.':view==='team'?'Delapan keahlian berbeda, satu tujuan yang sama.':'Hubungkan layanan yang dibutuhkan oleh kantor Anda.'}</p></div><div className="heading-actions"><button className="button secondary" onClick={()=>changeView('team')}><Users size={16}/>Lihat tim</button><button className="button primary" data-testid="new-campaign" onClick={()=>setCreateOpen(true)}><Plus size={17}/>Brief baru</button></div></section>}
    <section className="campaign-toolbar"><div className="campaign-picker"><span className="campaign-icon"><Layers3 size={17}/></span><div><span className="micro-label">CAMPAIGN AKTIF</span><select data-testid="campaign-select" aria-label="Campaign aktif" value={campaignId} onChange={e=>setCampaignId(e.target.value)}>{state.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><ChevronDown size={14}/></div><div className="campaign-meta">{campaign?.channels.map(c=><span key={c} className="channel-tag">{c}</span>)}<span className="toolbar-divider"/><span className="campaign-progress"><span className="progress-track"><i style={{width:`${progress}%`}}/></span>{progress}% disetujui</span></div><div className="run-controls">{view!=='office'&&<button className="button secondary" data-testid="new-campaign" onClick={()=>setCreateOpen(true)}><Plus size={15}/>Brief baru</button>}<select className={`mode-selector ${mode==='demo'?'demo':''}`} aria-label="Mode eksekusi" value={mode} onChange={e=>setMode(e.target.value as 'demo'|'live')}><option value="demo">Mode simulasi</option><option value="live" disabled={!config.aiConfigured}>OpenAI langsung{!config.aiConfigured?' · belum terhubung':''}</option></select><button className="button run-button" data-testid="run-campaign" disabled={busy||!campaignId} onClick={()=>safeAction({type:'runCampaign',campaignId,mode})}>{busy||runningCount>0?<LoaderCircle size={15} className="spin"/>:<Sparkles size={15}/>}<span>{busy||runningCount>0?'Tim sedang bekerja…':'Jalankan tim'}</span></button></div></section>
    {view==='office'?<>
     <div className={`office-workspace ${expanded?'office-expanded':''}`}>
      <section className="office-card"><div className="section-heading"><div className="section-title"><span className="small-icon"><Layers3 size={18}/></span><h2>Kantor virtual</h2><span className="pill live-pill">{runningCount?`${runningCount} agen bekerja`:'Siap bekerja'}</span></div><div className="office-heading-actions"><span className="office-engine">Powered by Claw3D</span><button className="icon-button" title="Perbesar kantor" aria-label={expanded?'Kecilkan kantor':'Perbesar kantor'} onClick={()=>setExpanded(!expanded)}><Maximize2 size={16}/></button></div></div>
       <div className="scene-tabs" role="group" aria-label="Filter divisi"><button className={selectedDivision==='all'?'selected':''} onClick={()=>setSelectedDivision('all')}>Seluruh kantor</button>{DIVISIONS.filter(d=>d.id!=='manager').map(d=><button key={d.id} className={selectedDivision===d.id?'selected':''} onClick={()=>setSelectedDivision(d.id)}><i style={{background:d.color}}/>{d.name}</button>)}</div>
       <div className="scene-container"><OfficeScene agents={state.agents} selectedDivision={selectedDivision} onSelectAgent={setSelectedAgent} overview={expanded} resetKey={resetKey}/><div className="scene-stamp"><span className="tiny-live-dot"/><span>MARKETING HQ</span><span className="stamp-line"/>Lantai 01</div><div className="scene-controls"><button aria-label="Reset sudut pandang" title="Reset sudut pandang" onClick={()=>setResetKey(k=>k+1)}><RotateCcw size={15}/></button><span/><button aria-label="Tampilkan seluruh kantor" title="Tampilkan seluruh kantor" onClick={()=>{setSelectedDivision('all');setResetKey(k=>k+1);}}><Focus size={17}/></button></div><div className="scene-help">Geser untuk memutar <span>·</span> Scroll untuk zoom <span>·</span> Klik agen untuk menyapa</div></div>
       <div className="office-footer"><div className="avatar-stack">{state.agents.filter(a=>a.division!=='manager').slice(0,5).map(a=><Avatar key={a.id} agent={a} size={27}/>)}<span>8 agen <strong>·</strong> 4 divisi</span></div><span className="manager-presence"><span className="tiny-live-dot"/>Anda berada di kantor</span></div>
      </section>
      <ChatPanel state={state} campaignId={campaignId} channel={channel} setChannel={setChannel} action={action} busy={busy} onSelectAgent={setSelectedAgent}/>
     </div>
     <section className="divisions-section"><div className="section-label-row"><h2>Divisi Anda <span>Tim kecil. Dampak besar.</span></h2><button className="text-button" onClick={()=>changeView('team')}>Lihat semua agen <ArrowRight size={14}/></button></div><div className="division-cards">{DIVISIONS.filter(d=>d.id!=='manager').map(d=>{const agents=state.agents.filter(a=>a.division===d.id);const divisionTasks=tasks.filter(t=>t.division===d.id);const ready=divisionTasks.filter(t=>t.status==='review').length;return <button className={`division-card ${selectedDivision===d.id?'selected':''}`} key={d.id} onClick={()=>{setSelectedDivision(d.id);setChannel(d.id);}}><div className="division-card-top"><span className="division-symbol" style={{background:d.tint,color:d.color}}>{d.id==='marketing'?<Radio size={20}/>:d.id==='design'?<Sparkles size={20}/>:d.id==='analytics'?<BarChart3 size={20}/>:<Send size={19}/>}</span><span className="team-badge">2 agen</span><ArrowUpRight size={16}/></div><h3>{d.name}</h3><p>{d.subtitle}</p><div className="division-card-bottom"><div className="avatar-stack">{agents.map(a=><Avatar key={a.id} agent={a} size={26}/>)}<span>{agents.map(a=>a.name).join(' & ')}</span></div><span className={`division-state ${ready?'needs-review':''}`}><i/>{ready?`${ready} review`:agents.some(a=>a.status==='working')?'Bekerja':'Siap'}</span></div></button>;})}</div></section>
     <div className="workflow-strip"><span className="workflow-strip-title"><Workflow size={16}/>Alur kerja Anda</span>{['Brief','Riset','Strategi & copy','Desain','Review Anda','Publikasi'].map((step,i)=><span className="workflow-step" key={step}><span className={i===0?'step-number completed':'step-number'}>{i===0?<Check size={11}/>:i+1}</span>{step}{i<5&&<ChevronRight size={13}/>}</span>)}<button onClick={()=>changeView('workflow')}>Buka alur <ArrowUpRight size={14}/></button></div>
    </>:<WorkPanels view={view} state={state} config={config} campaignId={campaignId} action={action} busy={busy} onSelectAgent={setSelectedAgent} refresh={refresh}/>}
    <footer className="page-footer"><span><Flower2 size={13}/>Dibangun untuk ide yang layak diwujudkan.</span><span>{mode==='demo'?'Simulasi · hasil contoh, bukan eksekusi AI langsung':'OpenAI · eksekusi AI langsung'}<i/>Marketing Office</span></footer>
   </main>
  </div>
  {toast&&<div role={toast.error?'alert':'status'} className={`toast ${toast.error?'error':''}`}>{toast.error?<Bell size={18}/>:<Check size={18}/>}<span>{toast.text}</span><button aria-label="Tutup pemberitahuan" onClick={()=>setToast(null)}><X size={16}/></button></div>}
  {createOpen&&<BriefModal busy={busy} onClose={()=>setCreateOpen(false)} onCreate={async brief=>{await action({type:'createCampaign',brief});setCreateOpen(false);setView('office');}}/>}
  {activeAgent&&<AgentModal agent={activeAgent} state={state} onClose={()=>setSelectedAgent(null)} onChat={()=>{setChannel(activeAgent.division==='manager'?'general':activeAgent.division);setSelectedAgent(null);setView('office');}}/>}
 </div>;
}

function ChatPanel({state,campaignId,channel,setChannel,action,busy,onSelectAgent}:{state:OfficeState;campaignId:string;channel:DivisionId|'general';setChannel:(channel:DivisionId|'general')=>void;action:(action:OfficeAction)=>Promise<void>;busy:boolean;onSelectAgent:(id:string)=>void}){
 const [content,setContent]=useState('');const [assignee,setAssignee]=useState('');const endRef=useRef<HTMLDivElement|null>(null);
 const messages=state.messages.filter(m=>(!m.campaignId||m.campaignId===campaignId)&&m.channel===channel);
 const count=messages.length;
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[count,channel]);
 async function send(event:FormEvent){event.preventDefault();if(!content.trim())return;try{await action({type:'sendMessage',content:content.trim(),channel,campaignId,...(assignee?{assignTo:assignee}:{})});setContent('');}catch{}}
 return <section className="chat-card"><div className="section-heading"><div className="section-title"><MessageCircle size={18}/><h2>Ruang diskusi</h2><span className="chat-member-count">9</span></div><span className="tiny-live-dot"/></div><div className="chat-channel-row"><Hash size={15}/><select aria-label="Pilih grup chat" value={channel} onChange={e=>setChannel(e.target.value as DivisionId|'general')}><option value="general">general · seluruh divisi</option>{DIVISIONS.filter(d=>d.id!=='manager').map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><ChevronDown size={13}/></div><div className="chat-pinned"><span className="pin-dot"/><p>Ruang untuk ide, arahan, dan laporan tim.<br/><strong>Anda memimpin percakapannya.</strong></p><Sparkles size={18}/></div><div className="chat-messages" aria-live="polite" aria-label="Pesan grup">{messages.length===0?<div className="chat-empty"><MessageCircle size={25}/><h3>Mulai percakapan</h3><p>Sapa tim atau kirim arahan pertama Anda.</p></div>:messages.map(m=>{const agent=state.agents.find(a=>a.id===m.senderId)??AGENTS[0];return <article className={`chat-message ${agent.id==='manager'?'from-manager':''}`} key={m.id}><button className="avatar-button" onClick={()=>onSelectAgent(agent.id)} aria-label={`Lihat ${agent.name}`}><Avatar agent={agent} size={31}/></button><div className="message-body"><div className="message-author"><button onClick={()=>onSelectAgent(agent.id)}>{agent.name}</button><span className={`role-tag ${agent.division==='manager'?'human':''}`}>{agent.division==='manager'?'Human':divisionById(agent.division).name}</span><time dateTime={m.createdAt}>{shortTime(m.createdAt)}</time></div><p>{m.content}</p>{m.taskId&&<span className="message-task"><Workflow size={11}/>Terhubung ke pekerjaan</span>}</div></article>;})}<div ref={endRef}/></div><form className="chat-composer" onSubmit={send}><textarea data-testid="chat-input" aria-label="Pesan atau perintah untuk tim" placeholder="Kirim arahan untuk tim Anda…" value={content} maxLength={8000} rows={2} onChange={e=>setContent(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(content.trim()&&!busy)void send(e);}}}/><div className="composer-actions"><div className="assign-select"><Plus size={14}/><select data-testid="chat-assignee" aria-label="Tugaskan kepada agen" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Pesan biasa</option>{state.agents.filter(a=>a.id!=='manager').map(a=><option key={a.id} value={a.id}>Tugaskan ke {a.name}</option>)}</select></div><button data-testid="chat-send" className="send-button" type="submit" disabled={!content.trim()||busy} aria-label="Kirim pesan"><ArrowRight size={17}/></button></div></form><span className="composer-hint">{assignee?'Pesan ini akan menjadi tugas untuk agen.':'Enter untuk kirim · Shift + Enter untuk baris baru'}</span></section>;
}

function BriefModal({busy,onClose,onCreate}:{busy:boolean;onClose:()=>void;onCreate:(brief:Brief)=>Promise<void>}){
 const [brief,setBrief]=useState<Brief>({name:'',product:'',audience:'',objective:'',channels:['Instagram','TikTok'],budget:'',deadline:''});
 const [error,setError]=useState('');const firstRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{firstRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[onClose]);
 const field=(key:keyof Brief,value:string)=>setBrief(current=>({...current,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setError('');try{await onCreate(brief);}catch(err){setError(err instanceof Error?err.message:'Brief belum tersimpan.');}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><section className="modal brief-modal" role="dialog" aria-modal="true" aria-labelledby="brief-title"><div className="modal-header"><span className="modal-icon"><Sparkles size={23}/></span><button className="icon-button" aria-label="Tutup brief" onClick={onClose} disabled={busy}><X size={20}/></button></div><div className="modal-intro"><span className="eyebrow">FROM AN IDEA TO SOMETHING GREAT</span><h2 id="brief-title">Apa yang ingin kita kerjakan?</h2><p>Satu brief yang jelas untuk menggerakkan seluruh tim Anda.</p></div><form onSubmit={submit}><label>Nama campaign<input ref={firstRef} data-testid="brief-name" required maxLength={160} placeholder="Contoh: Peluncuran menu musim panas" value={brief.name} onChange={e=>field('name',e.target.value)}/></label><label>Produk atau brand<textarea data-testid="brief-product" required maxLength={2000} rows={2} placeholder="Ceritakan produknya dan apa yang membuatnya berbeda." value={brief.product} onChange={e=>field('product',e.target.value)}/></label><div className="form-grid"><label>Target audiens<input data-testid="brief-audience" required maxLength={2000} placeholder="Siapa yang ingin Anda jangkau?" value={brief.audience} onChange={e=>field('audience',e.target.value)}/></label><label>Tujuan campaign<input data-testid="brief-objective" required maxLength={2000} placeholder="Misalnya: tingkatkan kunjungan toko" value={brief.objective} onChange={e=>field('objective',e.target.value)}/></label></div><label>Kanal publikasi</label><div className="channel-options">{CHANNELS.map(c=><label className={`channel-option ${brief.channels.includes(c)?'checked':''}`} key={c}><input type="checkbox" checked={brief.channels.includes(c)} onChange={e=>setBrief(b=>({...b,channels:e.target.checked?[...b.channels,c]:b.channels.filter(v=>v!==c)}))}/>{c}{brief.channels.includes(c)&&<Check size={13}/>}</label>)}</div><div className="form-grid"><label>Anggaran <span>(opsional)</span><input placeholder="Misalnya: Rp5.000.000" maxLength={160} value={brief.budget} onChange={e=>field('budget',e.target.value)}/></label><label>Target selesai <span>(opsional)</span><input type="date" value={brief.deadline} onChange={e=>field('deadline',e.target.value)}/></label></div><div className="brief-footnote"><ShieldCheck size={18}/><span>Hasil kerja tim menunggu persetujuan Anda sebelum siap dipublikasikan.</span></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Batal</button><button data-testid="brief-submit" type="submit" className="button primary" disabled={busy||!brief.channels.length}>{busy?<LoaderCircle className="spin" size={16}/>:<ArrowRight size={16}/>}Buat campaign</button></div></form></section></div>;
}

function AgentModal({agent,state,onClose,onChat}:{agent:Agent;state:OfficeState;onClose:()=>void;onChat:()=>void}){
 const division=divisionById(agent.division);const tasks=state.tasks.filter(t=>t.agentId===agent.id);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal agent-modal" role="dialog" aria-modal="true" aria-label={`Profil ${agent.name}`}><button className="icon-button agent-modal-close" aria-label="Tutup profil" onClick={onClose}><X size={19}/></button><div className="agent-profile-art" style={{background:division.tint}}><Avatar agent={agent} size={126}/><span className="agent-profile-dot" style={{background:division.color}}/></div><div className="agent-profile-info"><span className="eyebrow" style={{color:division.color}}>{division.name}</span><h2>{agent.name}{agent.id==='manager'&&<span> · Human</span>}</h2><p>{agent.role}</p><span className="pill">{agent.status==='working'?'Sedang bekerja':agent.status==='review'?'Menunggu review':agent.status==='error'?'Perlu perhatian':'Siap bekerja'}</span><div className="agent-responsibility"><strong>{agent.id==='manager'?'Pengarah utama kantor':'Tanggung jawab'}</strong><p>{agent.id==='manager'?'Memberi brief, mengarahkan semua divisi, meninjau laporan, dan menyetujui hasil akhir sebelum distribusi.':agent.division==='marketing'?'Mengubah insight menjadi strategi campaign dan copy yang relevan untuk audiens Anda.':agent.division==='design'?'Menyusun arah visual dan aset kreatif yang konsisten dengan identitas brand.':agent.division==='analytics'?'Menyusun riset, asumsi, KPI, serta analisis performa berdasarkan data yang tersedia.':'Meninjau kualitas editorial dan menyiapkan paket konten untuk publikasi setelah persetujuan Anda.'}</p></div><div className="agent-task-summary"><span>{tasks.length}<small>Pekerjaan</small></span><span>{tasks.filter(t=>t.status==='approved').length}<small>Disetujui</small></span><span>{tasks.filter(t=>t.status==='review').length}<small>Perlu review</small></span></div><button className="button primary full-width" onClick={onChat}><MessageCircle size={16}/>Buka ruang diskusi</button><span className="portrait-credit">Karakter dibuat dengan GPT Image</span></div></section></div>;
}

function AccessGate({onUnlock}:{onUnlock:()=>Promise<void>}){
 const [token,setToken]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const res=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});if(!res.ok)throw new Error('Token akses tidak sesuai.');await onUnlock();}catch(err){setError(err instanceof Error?err.message:'Gagal membuka kantor.');}finally{setBusy(false);}}
 return <main className="loading-page"><div className="brand-mark"><Flower2 size={28}/></div><h1>Selamat datang di Kadaka.</h1><p>Kantor ini memiliki akses terbatas untuk Marketing Manager.</p><form className="access-form" onSubmit={submit}><label>Token akses<input type="password" autoComplete="current-password" required value={token} onChange={e=>setToken(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Memeriksa…':'Masuk ke kantor'}<ArrowRight size={16}/></button></form></main>;
}
