'use client';
import {useState,type FormEvent} from 'react';
import {Check,KeyRound,Save,ShieldCheck,Sparkles} from 'lucide-react';
import type {OfficeAction,OfficeConfig} from '@/lib/office/types';
export interface TikTokCreator {creator_username:string;creator_nickname:string;privacy_level_options:string[];comment_disabled:boolean;duet_disabled:boolean;stitch_disabled:boolean;max_video_post_duration_sec:number;}
export async function loadTikTokCreator():Promise<TikTokCreator>{
 const response=await fetch('/api/office/tiktok/creator',{method:'POST'});const result=await response.json();
 if(!response.ok)throw new Error(result.error||'Koneksi TikTok gagal.');return result.creator;
}
export default function TikTokSettings({config,busy,action}:{config:OfficeConfig;busy:boolean;action:(a:OfficeAction)=>Promise<void>}){
 const status=config.tiktok;const [enabled,setEnabled]=useState(status.enabled);const [apiKey,setApiKey]=useState('');const [clearKey,setClearKey]=useState(false);
 const [testing,setTesting]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [creator,setCreator]=useState<TikTokCreator|null>(null);
 async function save(e:FormEvent){e.preventDefault();setError('');setMessage('');setCreator(null);try{await action({type:'saveTikTok',settings:{enabled,...(apiKey?{apiKey}:{}),clearKey}});setMessage('Token TikTok tersimpan terenkripsi.');setClearKey(false);}catch(err){setError(err instanceof Error?err.message:'Token belum tersimpan.');}finally{setApiKey('');}}
 async function test(){setTesting(true);setError('');setMessage('');setCreator(null);try{const account=await loadTikTokCreator();setCreator(account);setMessage(`Terhubung ke ${account.creator_nickname} (@${account.creator_username}). Belum ada video dikirim.`);}catch(err){setError(err instanceof Error?err.message:'Koneksi gagal.');}finally{setTesting(false);}}
 return <div className="backend-grid"><form className="backend-card" data-testid="tiktok-settings" onSubmit={save}>
  <div className="backend-card-title"><span className="backend-icon"><KeyRound size={21}/></span><div><h3>TikTok · Content Posting API</h3><p>Tim Publisher · Cleo & Kai</p></div><span className={`backend-status ${status.enabled&&status.configured?'connected':''}`}>{status.enabled&&status.configured?'Dikonfigurasi':'Belum aktif'}</span></div>
  <label className="backend-checkbox"><input data-testid="tiktok-enabled" type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Aktifkan koneksi Publisher TikTok</label>
  <label>Access token TikTok baru<input data-testid="tiktok-key" type="password" autoComplete="new-password" spellCheck={false} maxLength={4096} value={apiKey} placeholder="Kosongkan untuk mempertahankan token tersimpan" onChange={e=>{setApiKey(e.target.value);if(e.target.value)setClearKey(false);}}/><small>Gunakan user access token OAuth dengan scope video.publish. Client key / client secret aplikasi saja tidak dapat dipakai untuk publish.</small></label>
  <label className="backend-checkbox"><input data-testid="tiktok-clear" type="checkbox" checked={clearKey} onChange={e=>{setClearKey(e.target.checked);if(e.target.checked)setApiKey('');}}/>Hapus token dan nonaktifkan token environment</label>
  <div className="backend-key-state"><ShieldCheck size={14}/>{status.keySource==='stored'?'Token terenkripsi tersimpan di server':status.keySource==='environment'?'Token dari environment':'Belum ada token'}</div>
  {error&&<p role="alert" className="backend-error">{error}</p>}{message&&<p role="status" className="backend-success"><Check size={15}/>{message}</p>}
  {creator&&<p className="backend-footnote">Privasi tersedia: {creator.privacy_level_options.join(', ')}. Durasi video maksimum: {creator.max_video_post_duration_sec} detik.</p>}
  <div className="backend-actions"><button type="button" data-testid="tiktok-test" className="button secondary" disabled={busy||testing||!status.enabled||!status.configured} onClick={()=>void test()}><Sparkles size={15}/>{testing?'Menguji…':'Uji token & akun'}</button><button type="submit" data-testid="tiktok-save" className="button primary" disabled={busy||testing}><Save size={15}/>Simpan token TikTok</button></div>
 </form><aside className="backend-help"><section className="backend-card"><h3>Publish dari hasil pekerjaan.</h3><p>Setujui seluruh hasil kampanye, jadwalkan kanal TikTok, lalu buka Hasil pekerjaan. Saat jadwal tiba, pilih akun dan privasi, masukkan URL video final serta caption, lalu kirim dengan persetujuan manager.</p><p>Video harus tersedia di URL HTTPS pada domain/prefix yang telah diverifikasi pada aplikasi TikTok Anda. Kantor ini tidak membuat file video dari naskah AI.</p></section><section className="backend-card"><h3>Akses aplikasi TikTok.</h3><p>Aktifkan Content Posting API dan izin video.publish di TikTok for Developers. Aplikasi yang belum lolos audit TikTok dapat dibatasi ke posting privat. Pilihan privasi mengikuti akun, bukan diatur otomatis oleh kantor.</p><p>Token dapat kedaluwarsa. Masukkan token OAuth baru bila diperlukan; refresh token dan client secret tidak disimpan di fitur ini.</p><p>Uji token hanya membaca informasi creator. Menyimpan token, menyetujui hasil, dan membuat jadwal tidak mengirim video.</p></section></aside></div>;
}
