'use client';
import {useState,type FormEvent} from 'react';
import {Check,Save,ShieldCheck,Video} from 'lucide-react';
import type {OfficeAction,OfficeConfig,VideoAspectRatio} from '@/lib/office/types';
export default function VideoSettings({config,busy,action}:{config:OfficeConfig;busy:boolean;action:(a:OfficeAction)=>Promise<void>}){
 const [model,setModel]=useState(config.video.model);const [ratio,setRatio]=useState<VideoAspectRatio>(config.video.aspectRatio);const [key,setKey]=useState('');const [clear,setClear]=useState(false);const [testing,setTesting]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function save(e:FormEvent){e.preventDefault();setMessage('');setError('');try{await action({type:'saveVideoProvider',settings:{model,aspectRatio:ratio,...(key?{apiKey:key}:{}),clearKey:clear}});setClear(false);setMessage('Model video dan token tersimpan.');}catch(e){setError(e instanceof Error?e.message:'Konfigurasi belum tersimpan.');}finally{setKey('');}}
 async function test(){setTesting(true);setMessage('');setError('');try{const r=await fetch('/api/office/videos/test',{method:'POST'});const result=await r.json();if(!r.ok)throw new Error(result.error||'Pemeriksaan gagal.');setMessage(`Token valid dan ${result.model} tersedia. Izin inferensi dan saldo diperiksa saat generasi.`);}catch(e){setError(e instanceof Error?e.message:'Pemeriksaan gagal.');}finally{setTesting(false);}}
 return <div className="backend-grid"><form className="backend-card" data-testid="video-settings" onSubmit={save}><div className="backend-card-title"><span className="backend-icon"><Video size={21}/></span><div><h3>Generate Video</h3><p>Hugging Face Inference Providers · Graphic Design</p></div><span className={`backend-status ${config.video.configured?'connected':''}`}>{config.video.configured?'Dikonfigurasi':'Token diperlukan'}</span></div>
 <label>Model open source<select data-testid="video-model" value={model} onChange={e=>setModel(e.target.value)}><option value="Wan-AI/Wan2.2-T2V-A14B">Wan 2.2 · T2V A14B</option><option value="Wan-AI/Wan2.1-T2V-14B">Wan 2.1 · T2V 14B</option></select><small>Model Wan dengan bobot terbuka. Ketersediaan layanan fal-ai melalui Hugging Face diperiksa sebelum generasi.</small></label>
 <label>Rasio video<select data-testid="video-ratio" value={ratio} onChange={e=>setRatio(e.target.value as VideoAspectRatio)}><option value="16:9">16:9 · Landscape</option><option value="9:16">9:16 · TikTok / Reels</option><option value="1:1">1:1 · Persegi</option></select><small>Meminta resolusi 720p. Durasi dan rasio akhir mengikuti dukungan model/provider.</small></label>
 <label>Token Hugging Face video baru<input data-testid="video-key" type="password" autoComplete="new-password" spellCheck={false} maxLength={4096} placeholder="Kosongkan untuk mempertahankan token" value={key} onChange={e=>{setKey(e.target.value);if(e.target.value)setClear(false);}}/><small>Token hf_ dengan izin Inference Providers dan kredit. Token video disimpan terpisah dari FLUX.1, Gemini, dan Publisher.</small></label>
 <label className="backend-checkbox"><input data-testid="video-clear" type="checkbox" checked={clear} onChange={e=>{setClear(e.target.checked);if(e.target.checked)setKey('');}}/>Hapus token video dan nonaktifkan fallback environment</label>
 <div className="backend-key-state"><ShieldCheck size={14}/>{config.video.keySource==='stored'?'Token terenkripsi tersimpan':config.video.keySource==='environment'?'Token dari environment':'Belum ada token video'}</div>
 {error&&<p className="backend-error" role="alert">{error}</p>}{message&&<p className="backend-success" role="status"><Check size={15}/>{message}</p>}
 <div className="backend-actions"><button data-testid="video-test" type="button" className="button secondary" disabled={busy||testing||!config.video.configured} onClick={()=>void test()}>{testing?'Memeriksa…':'Periksa token & model'}</button><button data-testid="video-save" className="button primary" type="submit" disabled={busy||testing}><Save size={15}/>Simpan model video</button></div></form>
 <aside className="backend-help"><section className="backend-card"><h3>Brief menjadi klip video.</h3><p>Buka hasil Graphic Design lalu pilih Buat video. Prompt memakai brief dan arahan desain. Generasi dapat memerlukan beberapa menit, memakai kredit berbayar, dan menunggu hingga 8 menit.</p><p>Hasil MP4 tersimpan privat, bisa dipreview dan diekspor. Video baru membatalkan persetujuan hasil terkait agar Marketing Manager meninjaunya lagi.</p></section><section className="backend-card"><h3>Periksa sebelum membuat ulang.</h3><p>Tombol pemeriksaan hanya mengecek token dan pemetaan model; tidak membuat video atau memastikan saldo inferensi. Model yang belum dilayani akan menghasilkan pesan yang jelas.</p><p>Jika koneksi terputus, job dapat tetap berjalan di provider. Periksa akun sebelum mencoba ulang. Video tidak dipublikasikan otomatis; Publisher tetap memerlukan persetujuan dan tindakan manager.</p></section></aside></div>;
}
